---
version: '3.8'

services:
  jore4-tiamat:
    mem_limit: 2048m
    mem_reservation: 512M
    # build and the docker image from the local repo
    build:
      context: ..
    # Waiting for database to be ready to avoid startup delay due to initial crash
    # Note: this should only be done in development setups as Kubernetes does not allow waiting for services to be ready
    depends_on:
      jore4-testdb:
        condition: service_healthy
    # environment:
      # enabling the hasura console locally to ease development
      # HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
