apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.internalPort }}
    - name: debug
      port: {{ .Values.service.debugPort }}
      protocol: TCP
      targetPort: {{ .Values.service.debugPort }}
  selector:
    app: {{ .Release.Name }}
    version: {{ .Chart.Version }}
  sessionAffinity: None
  type: ClusterIP
