apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  name: {{ .Values.deployment.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.http.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.http.internalPort }}
    - name: hazelcast
      port: 5701
      protocol: TCP
      targetPort: 5701
  selector:
    app: {{ .Values.deployment.name }}
  sessionAffinity: None
  type: ClusterIP