name: CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run_java_tests:
    name: Run Java tests
    uses: ./.github/workflows/run-java-tests.yml

  push_to_registry:
    needs: run_java_tests
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract metadata to env variables
        uses: HSLdevcom/jore4-tools/github-actions/extract-metadata@extract-metadata-v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "arm64"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.JORE4_DOCKERHUB_USER }}
          password: ${{ secrets.JORE4_DOCKERHUB_TOKEN }}

      - name: Build and push dev builds to Docker Hub
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            --cache-from type=registry,ref=$IMAGE_NAME:builder \
            --cache-to type=registry,ref=$IMAGE_NAME:builder,mode=max \
            --tag $IMAGE_NAME:builder \
            .

          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            --cache-from type=registry,ref=$IMAGE_NAME:builder \
            --tag $IMAGE_NAME:$COMMIT_ID \
            .

      - name: Build and push :latest tag to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            --cache-from type=registry,ref=$IMAGE_NAME:builder \
            --tag $IMAGE_NAME:latest \
            .

  publish_docker_image_to_acr:
    needs:
      - run_java_tests
    name: Publish Docker image to ACR
    permissions:
      id-token: write
      contents: read
    uses: HSLdevcom/jore4-tools/.github/workflows/shared-build-and-publish-docker-image.yml@shared-build-and-publish-docker-image-v1
    with:
      docker_image_name: jore4-tiamat
      build_arm64_image: true
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  run_cypress_tests:
    needs:
      - run_java_tests
      - push_to_registry
    uses: ./.github/workflows/run-cypress-tests.yml
