name: CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Oslo
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Run tests
        run: |
          sudo timedatectl set-timezone "Europe/Oslo"
          mvn --batch-mode test


  image:
    # only build and push the image when it's a commit to master in Entur's repository
    if: github.repository_owner == 'entur' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [ tests ]
    env:
      CONTAINER_REPO: docker.io/entur/sobek
      CONTAINER_REGISTRY_USER: ${{ secrets.DOCKERHUB_LOGIN }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: set variables
        run: |
          echo "GHA_DOCKER_PUSH_IMAGE_TAG=`date +%Y-%m-%dT%H-%M`" >> $GITHUB_ENV

      - name: Build container image with Jib, push to container repo
        run: |
          mvn --batch-mode compile com.google.cloud.tools:jib-maven-plugin:build -Djib.to.tags=latest,${{ env.GHA_DOCKER_PUSH_IMAGE_TAG }}

      - name: Tag default branch with the container image tag ${{ env.GHA_DOCKER_PUSH_IMAGE_TAG }}
        id: tag-version
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git tag --annotate "$GHA_DOCKER_PUSH_IMAGE_TAG" -m "chore(tag): $GHA_DOCKER_PUSH_IMAGE_TAG [skip ci]" --force
          git push origin "$GHA_DOCKER_PUSH_IMAGE_TAG" --force