name: Run cypress tests

on:
  # this workflow is only called by others, won't be executed on itself
  # as it uses the pre-built docker image that is produced in the upstream job
  workflow_call:

jobs:
  run_cypress_tests:
    name: Run cypress e2e tests from Docker
    # These must run on ubuntu 22.04 or older.
    # The MS SQL server used by jore4-jore3-importer,
    # does not run on Linux kernels newer than 6.6.x.
    runs-on: ubuntu-22.04

    steps:
      - name: Extract metadata to env variables
        uses: HSLdevcom/jore4-tools/github-actions/extract-metadata@extract-metadata-v1

      - name: Setup environment and run e2e tests from GitHub action
        uses: HSLdevcom/jore4-tools/github-actions/run-ci@main
        with:
          tiamat_version: "${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }}"
